name: ELib
version: '${project.version}'
main: de.drachir000.library.enchantments.ELib
api-version: 1.17
authors: [ Drachir000 ]
description: A Minecraft plugin that acts as a library for other plugin developers, allowing them to easily create and manage custom enchantments. It also handles the lore, anvil, and other aspects of managing these enchantments. This library is notable for allowing multiple custom enchantment plugins to run seamlessly and without conflicts.
website: https://github.com/Drachir000/ELib
